In [ ]:
## link to investments. prioritse source that has investment & capacity.

In [40]:
import pandas as pd
import sys; sys.path.append("..")
from src.vote_helpers import fill_single_product_lv2, parse_capacity_value
from mongo_client import mongo_client, capacities_collection
from collections import defaultdict

try:
    mongo_client.admin.command("ping")
    print("✅ Connected to MongoDB Atlas!")
except Exception as e:
    print(f"❌ MongoDB Connection Error: {e}")
    raise

df = pd.read_excel("storage/output/filtered_projects_jul16.xlsx")
df['date'] = pd.to_datetime(df['date'], format='%Y-%m')

# fill product_lv2 across multiple NA rows
df = df.groupby("cluster_id").apply(fill_single_product_lv2).reset_index(drop=True)

# normalise capacity values
df["capacity_normalized"] = df["capacity_normalized"].apply(parse_capacity_value)

print(len(df))

print(len(df[(df["phase"] == "unclear")]))

print(len(df[df["status"] == "unclear"]))

print(len(df[df["date"].isna()]))

# drop all cases where phase | status are unclear

df = df[(df["phase"] != "unclear") & (df["status"] != "unclear")].copy()

df = df[~df["date"].isna()].copy()

print(len(df))

✅ Connected to MongoDB Atlas!
345
26
1
47
277

/var/folders/2d/7gfcftkd69s2z741sq98f0sc0000gn/T/ipykernel_35705/3256782809.py:18: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df = df.groupby("cluster_id").apply(fill_single_product_lv2).reset_index(drop=True)

In [43]:
df["clutser_id"].unique()

KeyError: 'clutser_id'

In [44]:
df[df["cluster_id"] == 43]

,inst_canon,city_key,adm1,adm2,iso2,cluster_id,product_lv1,product_lv2,product,capacity_normalized,capacity_metric_normalized,status,phase,date,article_id
23,man,nuremberg,Bavaria,Middle Franconia,DE,43,battery,module_pack,high-voltage batteries,2.5,GWh,announced,greenfield,2024-11-01,67f92305f431fddd61d56051
24,man,nuremberg,Bavaria,Middle Franconia,DE,43,battery,module_pack,high-voltage batteries,5.0,GWh,announced,expansion,2024-11-01,67f92305f431fddd61d56051

In [ ]:
import logging

# Remove all handlers associated with the root logger object (to avoid duplicate logs in Jupyter)
for handler in logging.root.handlers[:]:
    logging.root.removeHandler(handler)

# Set up logging to file and console
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler("votes_log.log", mode='w'),  # opening in write mode (overwriting each time)
        logging.StreamHandler()  # This keeps output in the notebook as well
    ]
)

# Example usage
logging.info("INITIATING LOGGING")
unique_clusters = df["cluster_id"].unique().tolist()
logging.info(f"Votes for {len(unique_clusters)} clusters.")
status_counts = defaultdict(int)

for cluster in unique_clusters:

    logging.info(f"Assessing votes for cluster_id: {cluster}")

    df_cluster = df[df["cluster_id"] == cluster].copy()
    unique_statuses = df_cluster["status"].unique()
    unique_phases = df_cluster["phase"].unique()

    owner = df_cluster["inst_canon"].unique()[0]
    iso2 = df_cluster["iso2"].unique()[0]
    adm1 = df_cluster["adm1"].unique()[0]
    product_lv1 = df_cluster["product_lv1"].unique()[0]

    if "announced" in unique_statuses and len(unique_statuses) <2:
        logging.info("⚪️ ANNOUNCED case")
        status_counts["announced"] += 1

        # only announcement so we ignore expansions 
        df_canon = df_cluster[df_cluster["phase"] != "expansion"]
        if len(df_canon) < 1:
            logging.info("🔴 ERROR - no greenfield phase noted at facility, only expansions. DROPPED.")
            status_counts["announced-dropped-only-expansions"] += 1
            continue

        dt_announce = df_canon["date"].min()
        phase = "greenfield"

        # find row with the latest date & take capacity
        row_latest = df_canon.loc[df_canon["date"].idxmax()]
        capacity_latest = row_latest["capacity_normalized"]
        
        dt_construct = None
        dt_operation = None

    elif "under construction" in unique_statuses and "operational" not in unique_statuses:
        logging.info("🔵 UNDER CONSTRUCTION case")
        status_counts["under-construction"] += 1

        # only under construction so we ignore expansions 
        df_canon = df_cluster[df_cluster["phase"] != "expansion"]
        if len(df_canon) < 1:
            logging.info("🔴 ERROR - no greenfield phase noted at facility, only expansions. DROPPED.")
            status_counts["under-construction-dropped-only-expansions"] += 1
            continue

        dt_announce = df_canon["date"].min()
        status = "under construction"
        phase = "greenfield"

        # Find row with the latest date & take capacity (for under construction cases)
        df_construct = df_canon[df_canon["status"] == "under construction"].copy()
        dt_construct = df_construct["date"].min()
        row_latest_construction = df_construct.loc[df_construct["date"].idxmax()]
        capacity_latest = row_latest["capacity_normalized"]
        
        dt_operation = None

    elif "operational" in unique_statuses:
        logging.info("🟢 OPERATIONAL case")
        status_counts["operational"] += 1

        # cases where there are no expansions
        if "expansion" not in unique_phases:
            logging.info("No expansions sub-case")
            status_counts["operational-no-expansions"] += 1

            # earliest date taken for dt_announce
            dt_announce = df_cluster["date"].min()    #the earliest date mentioned
            status = "operational"
            phase = "greenfield"

            # earliest date where status == under construction taken for dt_construct
            df_construct = df_cluster[df_cluster["status"] == "under construction"].copy()
            dt_construct = df_construct["date"].min()

            # earliest date where status == operational taken for dt_operation
            df_operation = df_cluster[df_cluster["status"] == "operational"].copy()
            dt_operation = df_cluster["date"].min()

            # take operational capacity from most recent article
            row_latest_operation = df_operation.loc[df_operation["date"].idxmax()]
            capacity_latest = row_latest["capacity_normalized"]

        if "expansion" in unique_phases:
            logging.info("With expansions sub-case")
            status_counts["operational-with-expansions"] += 1


    else:
        logging.info("Group not assigned")
        status_counts["unassigned"] += 1

# # final dictionary to insert to Mongo
#     mongo_entry = {
#         "owner": owner,
#         "iso2": iso2,
#         "adm1": adm1,
#         "product_lv1": product_lv1,
#         #"product": product_dict,
#         "dt_announce": dt_announce.strftime("%Y-%m") if pd.notnull(dt_announce) else None,
#         "status": "announced",
#         "phase": phase,
#         "capacity": capacity_latest,
#         "dt_construct": dt_construct.strftime("%Y-%m") if pd.notnull(dt_construct) else None,
#         "dt_operation": dt_operation.strftime("%Y-%m") if pd.notnull(dt_operation) else None
#     }

#     capacities_collection.insert_one(mongo_entry)
#     logging.info("✅ Inserted announced project into MongoDB.")

logging.info("📊 Final Status Counts:")
for status, count in status_counts.items():
    logging.info(f"{status}: {count}")

2025-07-17 16:55:59,891 - INFO - INITIATING LOGGING
2025-07-17 16:55:59,899 - INFO - Votes for 71 clusters.
2025-07-17 16:55:59,901 - INFO - Assessing votes for cluster_id: 2
2025-07-17 16:55:59,909 - INFO - 🔵 UNDER CONSTRUCTION case
2025-07-17 16:55:59,914 - INFO - Assessing votes for cluster_id: 35
2025-07-17 16:55:59,914 - INFO - 🔵 UNDER CONSTRUCTION case
2025-07-17 16:55:59,915 - INFO - Assessing votes for cluster_id: 37
2025-07-17 16:55:59,916 - INFO - 🔵 UNDER CONSTRUCTION case
2025-07-17 16:55:59,916 - INFO - Assessing votes for cluster_id: 39
2025-07-17 16:55:59,917 - INFO - 🔵 UNDER CONSTRUCTION case
2025-07-17 16:55:59,918 - INFO - Assessing votes for cluster_id: 41
2025-07-17 16:55:59,918 - INFO - 🟢 OPERATIONAL case
2025-07-17 16:55:59,919 - INFO - No expansions sub-case
2025-07-17 16:55:59,920 - INFO - Assessing votes for cluster_id: 42
2025-07-17 16:55:59,920 - INFO - 🟢 OPERATIONAL case
2025-07-17 16:55:59,921 - INFO - With expansions sub-case
2025-07-17 16:55:59,921 - INFO - Assessing votes for cluster_id: 43
2025-07-17 16:55:59,922 - INFO - ⚪️ ANNOUNCED case
2025-07-17 16:55:59,922 - INFO - Assessing votes for cluster_id: 49
2025-07-17 16:55:59,923 - INFO - 🟢 OPERATIONAL case
2025-07-17 16:55:59,923 - INFO - With expansions sub-case
2025-07-17 16:55:59,924 - INFO - Assessing votes for cluster_id: 50
2025-07-17 16:55:59,924 - INFO - 🔵 UNDER CONSTRUCTION case
2025-07-17 16:55:59,925 - INFO - Assessing votes for cluster_id: 51
2025-07-17 16:55:59,925 - INFO - ⚪️ ANNOUNCED case
2025-07-17 16:55:59,926 - INFO - Assessing votes for cluster_id: 53
2025-07-17 16:55:59,926 - INFO - ⚪️ ANNOUNCED case
2025-07-17 16:55:59,927 - INFO - Assessing votes for cluster_id: 56
2025-07-17 16:55:59,927 - INFO - ⚪️ ANNOUNCED case
2025-07-17 16:55:59,928 - INFO - Assessing votes for cluster_id: 85
2025-07-17 16:55:59,928 - INFO - ⚪️ ANNOUNCED case
2025-07-17 16:55:59,928 - INFO - Assessing votes for cluster_id: 88
2025-07-17 16:55:59,929 - INFO - 🟢 OPERATIONAL case
2025-07-17 16:55:59,929 - INFO - No expansions sub-case
2025-07-17 16:55:59,930 - INFO - Assessing votes for cluster_id: 90
2025-07-17 16:55:59,930 - INFO - ⚪️ ANNOUNCED case
2025-07-17 16:55:59,931 - INFO - Assessing votes for cluster_id: 94
2025-07-17 16:55:59,931 - INFO - ⚪️ ANNOUNCED case
2025-07-17 16:55:59,932 - INFO - Assessing votes for cluster_id: 97
2025-07-17 16:55:59,933 - INFO - ⚪️ ANNOUNCED case
2025-07-17 16:55:59,933 - INFO - Assessing votes for cluster_id: 98
2025-07-17 16:55:59,934 - INFO - ⚪️ ANNOUNCED case
2025-07-17 16:55:59,934 - INFO - 🔴 ERROR - no greenfield phase noted at facility, only expansions. DROPPED.
2025-07-17 16:55:59,934 - INFO - Assessing votes for cluster_id: 106
2025-07-17 16:55:59,935 - INFO - ⚪️ ANNOUNCED case
2025-07-17 16:55:59,935 - INFO - Assessing votes for cluster_id: 161
2025-07-17 16:55:59,936 - INFO - ⚪️ ANNOUNCED case
2025-07-17 16:55:59,936 - INFO - Assessing votes for cluster_id: 163
2025-07-17 16:55:59,936 - INFO - 🔵 UNDER CONSTRUCTION case
2025-07-17 16:55:59,937 - INFO - Assessing votes for cluster_id: 164
2025-07-17 16:55:59,937 - INFO - ⚪️ ANNOUNCED case
2025-07-17 16:55:59,938 - INFO - 🔴 ERROR - no greenfield phase noted at facility, only expansions. DROPPED.
2025-07-17 16:55:59,938 - INFO - Assessing votes for cluster_id: 167
2025-07-17 16:55:59,938 - INFO - 🔵 UNDER CONSTRUCTION case
2025-07-17 16:55:59,939 - INFO - Assessing votes for cluster_id: 168
2025-07-17 16:55:59,939 - INFO - ⚪️ ANNOUNCED case
2025-07-17 16:55:59,940 - INFO - Assessing votes for cluster_id: 172
2025-07-17 16:55:59,940 - INFO - ⚪️ ANNOUNCED case
2025-07-17 16:55:59,941 - INFO - Assessing votes for cluster_id: 174
2025-07-17 16:55:59,941 - INFO - ⚪️ ANNOUNCED case
2025-07-17 16:55:59,942 - INFO - Assessing votes for cluster_id: 176
2025-07-17 16:55:59,942 - INFO - ⚪️ ANNOUNCED case
2025-07-17 16:55:59,942 - INFO - 🔴 ERROR - no greenfield phase noted at facility, only expansions. DROPPED.
2025-07-17 16:55:59,942 - INFO - Assessing votes for cluster_id: 178
2025-07-17 16:55:59,943 - INFO - 🔵 UNDER CONSTRUCTION case
2025-07-17 16:55:59,943 - INFO - Assessing votes for cluster_id: 189
2025-07-17 16:55:59,944 - INFO - 🟢 OPERATIONAL case
2025-07-17 16:55:59,944 - INFO - With expansions sub-case
2025-07-17 16:55:59,944 - INFO - Assessing votes for cluster_id: 300
2025-07-17 16:55:59,945 - INFO - 🟢 OPERATIONAL case
2025-07-17 16:55:59,945 - INFO - No expansions sub-case
2025-07-17 16:55:59,946 - INFO - Assessing votes for cluster_id: 304
2025-07-17 16:55:59,946 - INFO - ⚪️ ANNOUNCED case
2025-07-17 16:55:59,946 - INFO - Assessing votes for cluster_id: 310
2025-07-17 16:55:59,947 - INFO - ⚪️ ANNOUNCED case
2025-07-17 16:55:59,947 - INFO - Assessing votes for cluster_id: 312
2025-07-17 16:55:59,948 - INFO - 🟢 OPERATIONAL case
2025-07-17 16:55:59,948 - INFO - With expansions sub-case
2025-07-17 16:55:59,948 - INFO - Assessing votes for cluster_id: 315
2025-07-17 16:55:59,948 - INFO - 🔵 UNDER CONSTRUCTION case
2025-07-17 16:55:59,949 - INFO - Assessing votes for cluster_id: 334
2025-07-17 16:55:59,950 - INFO - ⚪️ ANNOUNCED case
2025-07-17 16:55:59,950 - INFO - Assessing votes for cluster_id: 342
2025-07-17 16:55:59,951 - INFO - ⚪️ ANNOUNCED case
2025-07-17 16:55:59,952 - INFO - Assessing votes for cluster_id: 343
2025-07-17 16:55:59,952 - INFO - 🟢 OPERATIONAL case
2025-07-17 16:55:59,952 - INFO - With expansions sub-case
2025-07-17 16:55:59,953 - INFO - Assessing votes for cluster_id: 350
2025-07-17 16:55:59,953 - INFO - 🔵 UNDER CONSTRUCTION case
2025-07-17 16:55:59,954 - INFO - Assessing votes for cluster_id: 352
2025-07-17 16:55:59,954 - INFO - ⚪️ ANNOUNCED case
2025-07-17 16:55:59,954 - INFO - Assessing votes for cluster_id: 354
2025-07-17 16:55:59,955 - INFO - 🔵 UNDER CONSTRUCTION case
2025-07-17 16:55:59,955 - INFO - Assessing votes for cluster_id: 356
2025-07-17 16:55:59,956 - INFO - 🔵 UNDER CONSTRUCTION case
2025-07-17 16:55:59,956 - INFO - Assessing votes for cluster_id: 357
2025-07-17 16:55:59,956 - INFO - 🟢 OPERATIONAL case
2025-07-17 16:55:59,957 - INFO - With expansions sub-case
2025-07-17 16:55:59,957 - INFO - Assessing votes for cluster_id: 379
2025-07-17 16:55:59,957 - INFO - ⚪️ ANNOUNCED case
2025-07-17 16:55:59,958 - INFO - 🔴 ERROR - no greenfield phase noted at facility, only expansions. DROPPED.
2025-07-17 16:55:59,958 - INFO - Assessing votes for cluster_id: 381
2025-07-17 16:55:59,958 - INFO - ⚪️ ANNOUNCED case
2025-07-17 16:55:59,958 - INFO - Assessing votes for cluster_id: 385
2025-07-17 16:55:59,959 - INFO - ⚪️ ANNOUNCED case
2025-07-17 16:55:59,959 - INFO - 🔴 ERROR - no greenfield phase noted at facility, only expansions. DROPPED.
2025-07-17 16:55:59,959 - INFO - Assessing votes for cluster_id: 395
2025-07-17 16:55:59,960 - INFO - 🔵 UNDER CONSTRUCTION case
2025-07-17 16:55:59,960 - INFO - Assessing votes for cluster_id: 396
2025-07-17 16:55:59,961 - INFO - 🟢 OPERATIONAL case
2025-07-17 16:55:59,961 - INFO - No expansions sub-case
2025-07-17 16:55:59,962 - INFO - Assessing votes for cluster_id: 399
2025-07-17 16:55:59,963 - INFO - 🔵 UNDER CONSTRUCTION case
2025-07-17 16:55:59,963 - INFO - Assessing votes for cluster_id: 402
2025-07-17 16:55:59,964 - INFO - 🟢 OPERATIONAL case
2025-07-17 16:55:59,964 - INFO - With expansions sub-case
2025-07-17 16:55:59,964 - INFO - Assessing votes for cluster_id: 403
2025-07-17 16:55:59,965 - INFO - ⚪️ ANNOUNCED case
2025-07-17 16:55:59,965 - INFO - 🔴 ERROR - no greenfield phase noted at facility, only expansions. DROPPED.
2025-07-17 16:55:59,965 - INFO - Assessing votes for cluster_id: 405
2025-07-17 16:55:59,965 - INFO - ⚪️ ANNOUNCED case
2025-07-17 16:55:59,966 - INFO - Assessing votes for cluster_id: 408
2025-07-17 16:55:59,967 - INFO - 🟢 OPERATIONAL case
2025-07-17 16:55:59,967 - INFO - No expansions sub-case
2025-07-17 16:55:59,968 - INFO - Assessing votes for cluster_id: 409
2025-07-17 16:55:59,969 - INFO - 🔵 UNDER CONSTRUCTION case
2025-07-17 16:55:59,969 - INFO - Assessing votes for cluster_id: 410
2025-07-17 16:55:59,970 - INFO - 🔵 UNDER CONSTRUCTION case
2025-07-17 16:55:59,970 - INFO - Assessing votes for cluster_id: 411
2025-07-17 16:55:59,971 - INFO - ⚪️ ANNOUNCED case
2025-07-17 16:55:59,971 - INFO - Assessing votes for cluster_id: 439
2025-07-17 16:55:59,972 - INFO - ⚪️ ANNOUNCED case
2025-07-17 16:55:59,972 - INFO - Assessing votes for cluster_id: 446
2025-07-17 16:55:59,972 - INFO - 🔵 UNDER CONSTRUCTION case
2025-07-17 16:55:59,973 - INFO - 🔴 ERROR - no greenfield phase noted at facility, only expansions. DROPPED.
2025-07-17 16:55:59,973 - INFO - Assessing votes for cluster_id: 449
2025-07-17 16:55:59,973 - INFO - 🟢 OPERATIONAL case
2025-07-17 16:55:59,977 - INFO - With expansions sub-case
2025-07-17 16:55:59,978 - INFO - Assessing votes for cluster_id: 450
2025-07-17 16:55:59,980 - INFO - 🔵 UNDER CONSTRUCTION case
2025-07-17 16:55:59,982 - INFO - Assessing votes for cluster_id: 472
2025-07-17 16:55:59,985 - INFO - 🟢 OPERATIONAL case
2025-07-17 16:55:59,987 - INFO - With expansions sub-case
2025-07-17 16:55:59,989 - INFO - Assessing votes for cluster_id: 473
2025-07-17 16:55:59,992 - INFO - 🔵 UNDER CONSTRUCTION case
2025-07-17 16:55:59,997 - INFO - Assessing votes for cluster_id: 479
2025-07-17 16:55:59,999 - INFO - ⚪️ ANNOUNCED case
2025-07-17 16:56:00,003 - INFO - Assessing votes for cluster_id: 480
2025-07-17 16:56:00,005 - INFO - 🟢 OPERATIONAL case
2025-07-17 16:56:00,006 - INFO - No expansions sub-case
2025-07-17 16:56:00,011 - INFO - Assessing votes for cluster_id: 481
2025-07-17 16:56:00,014 - INFO - ⚪️ ANNOUNCED case
2025-07-17 16:56:00,016 - INFO - Assessing votes for cluster_id: 486
2025-07-17 16:56:00,021 - INFO - 🔵 UNDER CONSTRUCTION case
2025-07-17 16:56:00,023 - INFO - Assessing votes for cluster_id: 491
2025-07-17 16:56:00,024 - INFO - 🟢 OPERATIONAL case
2025-07-17 16:56:00,024 - INFO - With expansions sub-case
2025-07-17 16:56:00,024 - INFO - Assessing votes for cluster_id: 495
2025-07-17 16:56:00,025 - INFO - 🔵 UNDER CONSTRUCTION case
2025-07-17 16:56:00,025 - INFO - Assessing votes for cluster_id: 496
2025-07-17 16:56:00,026 - INFO - 🔵 UNDER CONSTRUCTION case
2025-07-17 16:56:00,026 - INFO - Assessing votes for cluster_id: 498
2025-07-17 16:56:00,027 - INFO - 🔵 UNDER CONSTRUCTION case
2025-07-17 16:56:00,027 - INFO - Assessing votes for cluster_id: 515
2025-07-17 16:56:00,028 - INFO - 🟢 OPERATIONAL case
2025-07-17 16:56:00,028 - INFO - No expansions sub-case
2025-07-17 16:56:00,028 - INFO - Assessing votes for cluster_id: 516
2025-07-17 16:56:00,029 - INFO - 🟢 OPERATIONAL case
2025-07-17 16:56:00,029 - INFO - No expansions sub-case
2025-07-17 16:56:00,030 - INFO - 📊 Final Status Counts:
2025-07-17 16:56:00,030 - INFO - under-construction: 23
2025-07-17 16:56:00,030 - INFO - operational: 18
2025-07-17 16:56:00,031 - INFO - operational-no-expansions: 8
2025-07-17 16:56:00,031 - INFO - operational-with-expansions: 10
2025-07-17 16:56:00,031 - INFO - announced: 30
2025-07-17 16:56:00,031 - INFO - announced-dropped-only-expansions: 6
2025-07-17 16:56:00,031 - INFO - under-construction-dropped-only-expansions: 1

In [32]:
df[df["cluster_id"] == 41]

,inst_canon,city_key,adm1,adm2,iso2,cluster_id,product_lv1,product_lv2,product,capacity_normalized,capacity_metric_normalized,status,phase,date,article_id
21,fenecon,iggensbach,Bavaria,Lower Bavaria,DE,41,battery,NaN,large-scale stationary storage systems,0.025,GWh,operational,greenfield,2024-04-01,67f922e7f431fddd61d55fee